spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-auth-demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123456
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true